#:kivy 1.0.9

# IMPORTANT: screen name specify in main.py
# sm.add_widget(SummaryScreen(name='summary'))
# sm.add_widget(StockScreen(name='stock'))

<TitleBar@BoxLayout>:
    screen_manager: None
    title_text: ''
    switch_screen: 'summary'
    switch_text: 'Summary'
    slide_direction: 'left'
    
    size_hint: 1, None
    height: '45sp'
    Label:
        text_size: self.size
        halign: 'left'
        valign: 'center'
        text: root.title_text
        font_size: '24sp'
    Button:
        size_hint: None, 1
        width: '150sp'
        text: root.switch_text
        font_size: '24sp'
        on_press:
            root.screen_manager.transition.direction = root.slide_direction
            root.screen_manager.current = root.switch_screen

<SummaryScreen>:
    BoxLayout:
        orientation: 'vertical'
        TitleBar:
            screen_manager: root.manager
            title_text: 'Eyedrop Summary'
            switch_screen: 'stock'
            switch_text: 'Stock'
            slide_direction: 'left'
        BoxLayout:
            Button:
                text: 'contents'

<StockScreen>:
    BoxLayout:
        orientation: 'vertical'
        TitleBar:
            screen_manager: root.manager
            title_text: 'Eyedrop Stock'
            switch_screen: 'summary'
            switch_text: 'Summary'
            slide_direction: 'right'
        BoxLayout:
            Button:
                text: 'contents'
